# Generated by Django 4.2.6 on 2023-10-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_publish_data_blogpost_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_data', '-updated', '-timestamp']},
        ),
    ]
